name: 🚀 Deploy website on FTP hosting
on:
    workflow_dispatch:
    push:
        tags:
            - 'prod.*'
            - 'staging.*'
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 🛠️ Create DB credentials
      run: |
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" > ./app/.env
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> ./app/.env
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> ./app/.env
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> ./app/.env
        echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> ./app/.env
        echo "TABLE_PREFIX=${{ vars.TABLE_PREFIX }}" >> ./app/.env

    - name: 🗃️ Initialize database schema
      run: |
        run: php ./cli.php migrate

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        server-dir: ${{ vars.SERVER_DIR }} #public_html/www/
        local-dir: ./app/
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{secrets.FTP_PORT}}
        exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**

            //91.216.107.187